version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: ecommerce_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - postgres
